In [1]:
import numpy as np

In [7]:
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [3]:
def mae(y_pred,y_true):
    total_err = 0
    for yt,yp in zip(y_true,y_pred):
        total_err += abs(yt-yp)
    print("Total error:",total_err)
    m = total_err/len(y_true)
    print("MAE:",m)

In [4]:
mae(y_pred,y_true)

Total error: 2.5
MAE: 0.5


In [10]:
# using numpy --> only if you have an numpy array => if normal array => gives an error
real_diff = (y_true-y_pred)
abs_diff = np.abs(y_true-y_pred)
print(real_diff)
print(abs_diff)

tot_err = np.sum(abs_diff)
print(tot_err)
mean_err = np.mean(abs_diff)
print(mean_err)

[-0.7 -0.3  1.   0.  -0.5]
[0.7 0.3 1.  0.  0.5]
2.5
0.5


In [11]:
# Binary Cross entropy

In [14]:
print(np.log([0]))
print(np.log([0.0000000000001]))    # log of value very close to 0 => treated as log of 0   => keep in mind in the formula

[-inf]
[-29.93360621]


C:\Users\Time\AppData\Local\Temp\ipykernel_8892\2818748229.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log([0]))


In [16]:
# Also we are taking log(1-y') in the formula => if pred=1 => log([0]) => problem
# Hence come up with epsilon

In [17]:
epsilon = 1e-15     # 0.000000000000001

In [18]:
y_pred

array([1, 1, 0, 0, 1])

In [19]:
# if we have 1, come up with a value close to 1 => (1-epsilon)
# if we have 0, come up with a value close to 0 => (epsilon)

In [20]:
y_pred_new = [max(i,epsilon) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [21]:
y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [22]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [24]:
ll = -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
print(ll)

17.2696280766844


In [25]:
def log_loss(y_true,y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [26]:
log_loss(y_true,y_pred)

17.2696280766844